# ~/.config/fuzzel/fuzzel.ini

[main]
font=Iosevka Nerd Font:size=10
terminal=kitty
prompt="❯ "
icon-theme=Papirus-Dark

width=54
lines=8

horizontal-pad=12
vertical-pad=8
inner-pad=6

layer=overlay
anchor=center

show-actions=no
icons-enabled=yes

[border]
width=1
radius=4

[colors]
background=000000ff
text=eeffffff
prompt=13ca91ff
placeholder=202020ff
input=eeffffff

match=13ca91ff
selection=13ca91ff
selection-text=000000ff
selection-match=000000ff

counter=7898fbff
border=202020ff
